# Generated by Django 3.1.5 on 2021-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.IntegerField()),
                ('pname', models.CharField(max_length=64)),
                ('pruns', models.IntegerField()),
                ('pfours', models.IntegerField()),
                ('psixes', models.IntegerField()),
            ],
        ),
    ]
